name: Convox Destroy
description: Delete a Convox app
author: Convox
inputs:
  rack:
    description: Convox Rack name
    required: true
  app:
    description: Convox app name
    required: true
runs:
  using: docker
  image: Dockerfile